### ISSUE TITLE
Cannot connect securely

### ISSUE THREAD

**Issue by DANW999** [tabjy/electronic-plex#13]
Hi all,

I have managed to build the app and its opens fine but I am getting the app.tv.plex cannot connect to server securely message, so it seems this app is trying to use remote access which I do not have access. Does this app require the remote access function or is it not able to connect to the Plex Server as long as it's on the local network. All the other Plex apps on my network connect just fine without remote access. I even get this issue with the Snap version. Any help is greatly appreciated!

**Comment by tabjy** [comment]
The project is actually just a simple electron wrapper connecting to [app.plex.tv](https://app.plex.tv/) which is basically a front end web app  accessing your media server via XHR. Can you confirm you have access to [app.plex.tv](https://app.plex.tv/) via a web browser and the app communicate to your media server properly?

If you want use the front end provided directly from your local server, try changing [this line](https://github.com/tabjy/electronic-plex/blob/acbd847443ef209ec8673ed70b7a24d67464cec5/src/index.html#L16). Sorry it's hardcoded.

Unfortunately I stopped using Plex and switched to Jellyfin so I don't have a working media server to try this. Let me know if you run into further problems. :)

**Comment by DANW999** [comment]
> The project is actually just a simple electron wrapper connecting to [app.plex.tv](https://app.plex.tv/) which is basically a front end web app accessing your media server via XHR. Can you confirm you have access to [app.plex.tv](https://app.plex.tv/) via a web browser and the app communicate to your media server properly?
> 
> If you want use the front end provided directly from your local server, try changing [this line](https://github.com/tabjy/electronic-plex/blob/acbd847443ef209ec8673ed70b7a24d67464cec5/src/index.html#L16). Sorry it's hardcoded.
> 
> Unfortunately I stopped using Plex and switched to Jellyfin so I don't have a working media server to try this. Let me know if you run into further problems. :)

Yeah, it does technically work but now I am bumping into playback issues, presumably due to transcoding issues because as you said its an electron wrapper, so its as a limited as a browser. Thanks for your help anyway
